"""order in questions it is not more unique

Revision ID: 255f4c050e2c
Revises: 31780f636d50
Create Date: 2025-08-01 17:33:57.354624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255f4c050e2c'
down_revision: Union[str, Sequence[str], None] = '31780f636d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transportations')
    op.alter_column('questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('questions_order_key'), 'questions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('questions_order_key'), 'questions', ['order'], postgresql_nulls_not_distinct=False)
    op.alter_column('questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('transportations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transportation_details', sa.VARCHAR(length=10000), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('transportations_pkey'))
    )
    # ### end Alembic commands ###
