"""change the nullable codndition for traveler_type_id in tuser_traveler_test

Revision ID: 31780f636d50
Revises: 7a30ca90c8ea
Create Date: 2025-08-01 16:43:40.671971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31780f636d50'
down_revision: Union[str, Sequence[str], None] = '7a30ca90c8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transportations')
    op.alter_column('user_traveler_tests', 'traveler_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_traveler_tests', 'traveler_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('transportations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transportation_details', sa.VARCHAR(length=10000), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('transportations_pkey'))
    )
    # ### end Alembic commands ###
