"""add metadata JSON field to itinerary

Revision ID: 65e0eec42de9
Revises: cec3d8961b5e
Create Date: 2025-10-02 15:42:07.474698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65e0eec42de9'
down_revision: Union[str, Sequence[str], None] = 'cec3d8961b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('itinerary_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('itineraries', 'itinerary_metadata')
    # ### end Alembic commands ###
